name: Mirror to Codeberg

on:
  push:
    branches: ["**"]
    tags: ["**"]
  delete:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror to Codeberg
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          CB_USER="hcousin"
          CB_TOKEN="${{ secrets.CODEBERG_TOKEN }}"
          GH_TOKEN="${{ secrets.GH_PAT }}"

          git clone --bare "https://x-token-auth:${GH_TOKEN}@github.com/${{ github.repository }}.git" repo_bare
          cd repo_bare
          git push --mirror "https://${CB_USER}:${CB_TOKEN}@codeberg.org/${CB_USER}/${REPO_NAME}.git"
